user:
    role: User (develop)
#   password: user_develop
    password: '{cipher}AQBG4sh7KZZrnS2BVb+9jZcTG3iZ7FmJdFsUIr0LYaSqhooqvo5dV1Co1BL09Cvshf4LPJvdOBUTKVsXa9K9AushYNbWjwzMBIIyYfm0zOqBahnQ0M5t9PdjUZyVLUz2VkG7PW+GfnPb/nL3qBUNydeP3tr6ey6cgTUS2afDv48sHkdMNFHFaDYGeb/PkyogRgrMt99y9Cc7gu8IK7tOfQG+ENuPksDxVCZvBRRP+Sa9xa7qQ1qVAMnJosoD14ivL4sm8bP6xbb7OCv6DQZFwc7occyJe9yvpxKcC+Rah6LNTQ48gpyovDcbrv9qp46Q/N70ND8wgBD2z0Po2tCLMegagUp8yBe/B6sHHqOcyf/Lt+FJUv4Odq1Eacn6pELp2dQ='